resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      students:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      students:
        base-config: defecto

spring:
  cloud:
    gateway:
      routes:
        - id: service-students
          uri: lb://service-students
          predicates:
            - Path=/api/students/**
          filters:
            - name: CircuitBreaker
              args:
                name: students
                statusCodes: 500
#                fallbackUri: forward:/api/students/students/1
            - StripPrefix=2


        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: servicio-oauth
          uri: lb://service-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
